"""Add email to patients

Revision ID: 403d9c222d2a
Revises: 09dad689d7f1
Create Date: 2026-07-24 10:41:33.926746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403d9c222d2a'
down_revision: Union[str, Sequence[str], None] = '09dad689d7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'patients', ['email'])
    op.create_foreign_key(None, 'patients', 'users', ['email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###
